In [ ]:
#Use Raw Strings (r"")
#If the error is from a file path, prefix it with r to make it a raw string:

In [7]:
import chardet
with open(r'D:\Dataset\URL\PhiUSIIL_Phishing_URL_Dataset.csv','rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

In [9]:
import pandas as pd
df = pd.read_csv(r'D:\Dataset\URL\PhiUSIIL_Phishing_URL_Dataset.csv',encoding='UTF-8-SIG')

In [10]:
df.columns
df.head

<bound method NDFrame.head of                                                       URL  URLLength  \
0                        https://www.southbankmosaics.com         31
1                                https://www.uni-mainz.de         23
2                          https://www.voicefmradio.co.uk         29
3                             https://www.sfnmjournal.com         26
4                      https://www.rewildingargentina.org         33
...                                                   ...        ...
235790                     https://www.skincareliving.com         29
235791                      https://www.winchester.gov.uk         28
235792                    https://www.nononsensedesign.be         30
235793  https://patient-cell-40f5.updatedlogmylogin.wo...         55
235794                 https://www.alternativefinland.com         33

                                                 Domain  DomainLength  \
0                              www.southbankmosaics.com            24
1                                      www.uni-mainz.de            16
2                                www.voicefmradio.co.uk            22
3                                   www.sfnmjournal.com            19
4                            www.rewildingargentina.org            26
...                                                 ...           ...
235790                           www.skincareliving.com            22
235791                            www.winchester.gov.uk            21
235792                          www.nononsensedesign.be            23
235793  patient-cell-40f5.updatedlogmylogin.workers.dev            47
235794                       www.alternativefinland.com            26

        IsDomainIP  TLD  URLSimilarityIndex  CharContinuationRate  \
0                0  com          100.000000              1.000000
1                0   de          100.000000              0.666667
2                0   uk          100.000000              0.866667
3                0  com          100.000000              1.000000
4                0  org          100.000000              1.000000
...            ...  ...                 ...                   ...
235790           0  com          100.000000              1.000000
235791           0   uk          100.000000              0.785714
235792           0   be          100.000000              1.000000
235793           0  dev           28.157537              0.465116
235794           0  com          100.000000              1.000000

        TLDLegitimateProb  URLCharProb  ...  Pay  Crypto  HasCopyrightInfo  \
0                0.522907     0.061933  ...    0       0                 1
1                0.032650     0.050207  ...    0       0                 1
2                0.028555     0.064129  ...    0       0                 1
3                0.522907     0.057606  ...    1       1                 1
4                0.079963     0.059441  ...    1       0                 1
...                   ...          ...  ...  ...     ...               ...
235790           0.522907     0.058739  ...    1       0                 1
235791           0.028555     0.053834  ...    1       0                 0
235792           0.003319     0.063093  ...    0       0                 1
235793           0.000961     0.050211  ...    0       0                 0
235794           0.522907     0.060596  ...    0       0                 1

        NoOfImage  NoOfCSS  NoOfJS  NoOfSelfRef  NoOfEmptyRef  \
0              34       20      28          119             0
1              50        9       8           39             0
2              10        2       7           42             2
3               3       27      15           22             1
4             244       15      34           72             1
...           ...      ...     ...          ...           ...
235790         51        7      21          187             2
235791         50        1       7           88             0
235792         27       10      30           58             2
235793          0        0       3            0             0
235794         21        6      18          256             0

        NoOfExternalRef  label
0                   124      1
1                   217      1
2                     5      1
3                    31      1
4                    85      1
...                 ...    ...
235790              191      1
235791               31      1
235792               67      1
235793                0      0
235794              261      1

[235795 rows x 55 columns]>

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 55 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URL                         235795 non-null  object
 1   URLLength                   235795 non-null  int64
 2   Domain                      235795 non-null  object
 3   DomainLength                235795 non-null  int64
 4   IsDomainIP                  235795 non-null  int64
 5   TLD                         235795 non-null  object
 6   URLSimilarityIndex          235795 non-null  float64
 7   CharContinuationRate        235795 non-null  float64
 8   TLDLegitimateProb           235795 non-null  float64
 9   URLCharProb                 235795 non-null  float64
 10  TLDLength                   235795 non-null  int64
 11  NoOfSubDomain               235795 non-null  int64
 12  HasObfuscation              235795 non-null  int64
 13  NoOfObfuscatedChar          235795 non-null  int64
 14  ObfuscationRatio            235795 non-null  float64
 15  NoOfLettersInURL            235795 non-null  int64
 16  LetterRatioInURL            235795 non-null  float64
 17  NoOfDegitsInURL             235795 non-null  int64
 18  DegitRatioInURL             235795 non-null  float64
 19  NoOfEqualsInURL             235795 non-null  int64
 20  NoOfQMarkInURL              235795 non-null  int64
 21  NoOfAmpersandInURL          235795 non-null  int64
 22  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 23  SpacialCharRatioInURL       235795 non-null  float64
 24  IsHTTPS                     235795 non-null  int64
 25  LineOfCode                  235795 non-null  int64
 26  LargestLineLength           235795 non-null  int64
 27  HasTitle                    235795 non-null  int64
 28  Title                       235795 non-null  object
 29  DomainTitleMatchScore       235795 non-null  float64
 30  URLTitleMatchScore          235795 non-null  float64
 31  HasFavicon                  235795 non-null  int64
 32  Robots                      235795 non-null  int64
 33  IsResponsive                235795 non-null  int64
 34  NoOfURLRedirect             235795 non-null  int64
 35  NoOfSelfRedirect            235795 non-null  int64
 36  HasDescription              235795 non-null  int64
 37  NoOfPopup                   235795 non-null  int64
 38  NoOfiFrame                  235795 non-null  int64
 39  HasExternalFormSubmit       235795 non-null  int64
 40  HasSocialNet                235795 non-null  int64
 41  HasSubmitButton             235795 non-null  int64
 42  HasHiddenFields             235795 non-null  int64
 43  HasPasswordField            235795 non-null  int64
 44  Bank                        235795 non-null  int64
 45  Pay                         235795 non-null  int64
 46  Crypto                      235795 non-null  int64
 47  HasCopyrightInfo            235795 non-null  int64
 48  NoOfImage                   235795 non-null  int64
 49  NoOfCSS                     235795 non-null  int64
 50  NoOfJS                      235795 non-null  int64
 51  NoOfSelfRef                 235795 non-null  int64
 52  NoOfEmptyRef                235795 non-null  int64
 53  NoOfExternalRef             235795 non-null  int64
 54  label                       235795 non-null  int64
dtypes: float64(10), int64(41), object(4)
memory usage: 98.9+ MB

In [13]:
list(df.columns.values)

['URL',
 'URLLength',
 'Domain',
 'DomainLength',
 'IsDomainIP',
 'TLD',
 'URLSimilarityIndex',
 'CharContinuationRate',
 'TLDLegitimateProb',
 'URLCharProb',
 'TLDLength',
 'NoOfSubDomain',
 'HasObfuscation',
 'NoOfObfuscatedChar',
 'ObfuscationRatio',
 'NoOfLettersInURL',
 'LetterRatioInURL',
 'NoOfDegitsInURL',
 'DegitRatioInURL',
 'NoOfEqualsInURL',
 'NoOfQMarkInURL',
 'NoOfAmpersandInURL',
 'NoOfOtherSpecialCharsInURL',
 'SpacialCharRatioInURL',
 'IsHTTPS',
 'LineOfCode',
 'LargestLineLength',
 'HasTitle',
 'Title',
 'DomainTitleMatchScore',
 'URLTitleMatchScore',
 'HasFavicon',
 'Robots',
 'IsResponsive',
 'NoOfURLRedirect',
 'NoOfSelfRedirect',
 'HasDescription',
 'NoOfPopup',
 'NoOfiFrame',
 'HasExternalFormSubmit',
 'HasSocialNet',
 'HasSubmitButton',
 'HasHiddenFields',
 'HasPasswordField',
 'Bank',
 'Pay',
 'Crypto',
 'HasCopyrightInfo',
 'NoOfImage',
 'NoOfCSS',
 'NoOfJS',
 'NoOfSelfRef',
 'NoOfEmptyRef',
 'NoOfExternalRef',
 'label']

In [14]:
columns_to_drop = ['URLLength',
 'Domain',
 'DomainLength',
 'IsDomainIP',
 'TLD',
 'URLSimilarityIndex',
 'CharContinuationRate',
 'TLDLegitimateProb',
 'URLCharProb',
 'TLDLength',
 'NoOfSubDomain',
 'HasObfuscation',
 'NoOfObfuscatedChar',
 'ObfuscationRatio',
 'NoOfLettersInURL',
 'LetterRatioInURL',
 'NoOfDegitsInURL',
 'DegitRatioInURL',
 'NoOfEqualsInURL',
 'NoOfQMarkInURL',
 'NoOfAmpersandInURL',
 'NoOfOtherSpecialCharsInURL',
 'SpacialCharRatioInURL',
 'IsHTTPS']
df = df.drop(columns= columns_to_drop)
df.columns
df.isnull().sum()

URL                      0
LineOfCode               0
LargestLineLength        0
HasTitle                 0
Title                    0
DomainTitleMatchScore    0
URLTitleMatchScore       0
HasFavicon               0
Robots                   0
IsResponsive             0
NoOfURLRedirect          0
NoOfSelfRedirect         0
HasDescription           0
NoOfPopup                0
NoOfiFrame               0
HasExternalFormSubmit    0
HasSocialNet             0
HasSubmitButton          0
HasHiddenFields          0
HasPasswordField         0
Bank                     0
Pay                      0
Crypto                   0
HasCopyrightInfo         0
NoOfImage                0
NoOfCSS                  0
NoOfJS                   0
NoOfSelfRef              0
NoOfEmptyRef             0
NoOfExternalRef          0
label                    0
dtype: int64

In [15]:
list(df.columns.values)

['URL',
 'LineOfCode',
 'LargestLineLength',
 'HasTitle',
 'Title',
 'DomainTitleMatchScore',
 'URLTitleMatchScore',
 'HasFavicon',
 'Robots',
 'IsResponsive',
 'NoOfURLRedirect',
 'NoOfSelfRedirect',
 'HasDescription',
 'NoOfPopup',
 'NoOfiFrame',
 'HasExternalFormSubmit',
 'HasSocialNet',
 'HasSubmitButton',
 'HasHiddenFields',
 'HasPasswordField',
 'Bank',
 'Pay',
 'Crypto',
 'HasCopyrightInfo',
 'NoOfImage',
 'NoOfCSS',
 'NoOfJS',
 'NoOfSelfRef',
 'NoOfEmptyRef',
 'NoOfExternalRef',
 'label']

In [18]:
df

,URL,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,20,28,119,0,124,1
1,https://www.uni-mainz.de,9,8,39,0,217,1
2,https://www.voicefmradio.co.uk,2,7,42,2,5,1
3,https://www.sfnmjournal.com,27,15,22,1,31,1
4,https://www.rewildingargentina.org,15,34,72,1,85,1
...,...,...,...,...,...,...,...
235790,https://www.skincareliving.com,7,21,187,2,191,1
235791,https://www.winchester.gov.uk,1,7,88,0,31,1
235792,https://www.nononsensedesign.be,10,30,58,2,67,1
235793,https://patient-cell-40f5.updatedlogmylogin.wo...,0,3,0,0,0,0
235794,https://www.alternativefinland.com,6,18,256,0,261,1

In [19]:
list(df.columns.values)

['URL',
 'NoOfCSS',
 'NoOfJS',
 'NoOfSelfRef',
 'NoOfEmptyRef',
 'NoOfExternalRef',
 'label']

In [20]:
columns_to_drop = ['NoOfCSS',
 'NoOfJS',
 'NoOfSelfRef',
 'NoOfEmptyRef',
 'NoOfExternalRef']
df = df.drop(columns= columns_to_drop)
df.columns
df.isnull().sum()

URL      0
label    0
dtype: int64

In [21]:
df

                                                      URL  label
0                        https://www.southbankmosaics.com      1
1                                https://www.uni-mainz.de      1
2                          https://www.voicefmradio.co.uk      1
3                             https://www.sfnmjournal.com      1
4                      https://www.rewildingargentina.org      1
...                                                   ...    ...
235790                     https://www.skincareliving.com      1
235791                      https://www.winchester.gov.uk      1
235792                    https://www.nononsensedesign.be      1
235793  https://patient-cell-40f5.updatedlogmylogin.wo...      0
235794                 https://www.alternativefinland.com      1

[235795 rows x 2 columns]

In [23]:
df['type'] = df['label'].replace({0:'phishing', 1: 'legitimate'})
df

                                                      URL  label        type
0                        https://www.southbankmosaics.com      1  legitimate
1                                https://www.uni-mainz.de      1  legitimate
2                          https://www.voicefmradio.co.uk      1  legitimate
3                             https://www.sfnmjournal.com      1  legitimate
4                      https://www.rewildingargentina.org      1  legitimate
...                                                   ...    ...         ...
235790                     https://www.skincareliving.com      1  legitimate
235791                      https://www.winchester.gov.uk      1  legitimate
235792                    https://www.nononsensedesign.be      1  legitimate
235793  https://patient-cell-40f5.updatedlogmylogin.wo...      0    phishing
235794                 https://www.alternativefinland.com      1  legitimate

[235795 rows x 3 columns]

In [24]:
df = df.drop(columns= ['label'])
df

                                                      URL        type
0                        https://www.southbankmosaics.com  legitimate
1                                https://www.uni-mainz.de  legitimate
2                          https://www.voicefmradio.co.uk  legitimate
3                             https://www.sfnmjournal.com  legitimate
4                      https://www.rewildingargentina.org  legitimate
...                                                   ...         ...
235790                     https://www.skincareliving.com  legitimate
235791                      https://www.winchester.gov.uk  legitimate
235792                    https://www.nononsensedesign.be  legitimate
235793  https://patient-cell-40f5.updatedlogmylogin.wo...    phishing
235794                 https://www.alternativefinland.com  legitimate

[235795 rows x 2 columns]

In [25]:
df.drop_duplicates()

                                                      URL        type
0                        https://www.southbankmosaics.com  legitimate
1                                https://www.uni-mainz.de  legitimate
2                          https://www.voicefmradio.co.uk  legitimate
3                             https://www.sfnmjournal.com  legitimate
4                      https://www.rewildingargentina.org  legitimate
...                                                   ...         ...
235790                     https://www.skincareliving.com  legitimate
235791                      https://www.winchester.gov.uk  legitimate
235792                    https://www.nononsensedesign.be  legitimate
235793  https://patient-cell-40f5.updatedlogmylogin.wo...    phishing
235794                 https://www.alternativefinland.com  legitimate

[235370 rows x 2 columns]

In [28]:
df = df.rename(columns={"URL":"url"})
df

                                                      url        type
0                        https://www.southbankmosaics.com  legitimate
1                                https://www.uni-mainz.de  legitimate
2                          https://www.voicefmradio.co.uk  legitimate
3                             https://www.sfnmjournal.com  legitimate
4                      https://www.rewildingargentina.org  legitimate
...                                                   ...         ...
235790                     https://www.skincareliving.com  legitimate
235791                      https://www.winchester.gov.uk  legitimate
235792                    https://www.nononsensedesign.be  legitimate
235793  https://patient-cell-40f5.updatedlogmylogin.wo...    phishing
235794                 https://www.alternativefinland.com  legitimate

[235795 rows x 2 columns]

In [31]:
df.to_csv(r"D:\Dataset\URL\PhiUSIIL_Phishing_URL_Dataset.csv", index=False)